import { test, expect } from '@playwright/test';
import path from 'path';
import { fileURLToPath } from 'url';
import { runDevCommand, killProcess } from '../../e2e/utils.ts';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

test.describe('rspress-plugin-mermaid', () => {
  let devProcess: any;
  let url: string;

  test.beforeAll(async () => {
    const result = await runDevCommand(__dirname);
    devProcess = result.process;
    url = result.url;
  });

  test.afterAll(async () => {
    if (devProcess) {
      await killProcess(devProcess);
    }
  });

  test('should render mermaid diagram', async ({ page }) => {
    await page.goto(url, { waitUntil: 'networkidle' });
    // Check if mermaid svg element exists, which is generated by mermaid
    const mermaidSvg = page.locator('svg[id^="_r_"]');
    await expect(mermaidSvg).toBeVisible();
  });
});
