import { test, expect } from '@playwright/test';
import path from 'path';
import { fileURLToPath } from 'url';
import { runDevCommand, killProcess } from '../../e2e/utils.ts';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

test.describe('rspress-plugin-katex', () => {
  let devProcess: any;
  let url: string;

  test.beforeAll(async () => {
    const result = await runDevCommand(__dirname);
    devProcess = result.process;
    url = result.url;
  });

  test.afterAll(async () => {
    if (devProcess) {
      await killProcess(devProcess);
    }
  });

  test('should render katex math', async ({ page }) => {
    await page.goto(url, { waitUntil: 'networkidle' });
    // Check if katex-html element exists, which is generated by katex
    const katexElement = page.locator('.katex-html');
    await expect(katexElement).toBeVisible();
  });
});