import { page } from '@rstest/browser';
import { render } from '@rstest/browser-react';
import { describe, expect, rs, test } from '@rstest/core';
import { reactDom } from '../src/components/reactDom';
import { YouTubeEmbed } from '../src/components/YouTubeEmbed';

describe('YouTubeEmbed Component', () => {
  test('renders YouTube embed custom element with correct video ID', async () => {
    await render(<YouTubeEmbed videoid="sSbDtQTtwBY" />);

    // Query the <lite-youtube> custom element rendered by third-party-capital
    const embedLocator = page.locator('lite-youtube');

    // Assert element presence and attribute using Rstest's expect.element matcher
    await expect.element(embedLocator).toBeVisible();
    await expect
      .element(embedLocator)
      .toHaveAttribute('videoid', 'sSbDtQTtwBY');
  });

  test('passes height, width, and playlabel props correctly', async () => {
    await render(
      <YouTubeEmbed
        videoid="sSbDtQTtwBY"
        width={640}
        height={360}
        playlabel="Play Demo Video"
      />,
    );

    const embedLocator = page.locator('lite-youtube');

    await expect.element(embedLocator).toBeVisible();
    await expect
      .element(embedLocator)
      .toHaveAttribute('playlabel', 'Play Demo Video');
  });

  test('invokes ReactDOM.preconnect for cdn.jsdelivr.net', async () => {
    // ReactDOM.preconnect
    const preconnectSpy = rs.fn();
    const originalPreconnect = reactDom.preconnect;
    reactDom.preconnect = preconnectSpy;
    try {
      await render(<YouTubeEmbed videoid="sSbDtQTtwBY" />);

      // Verify preconnect function was called with correct origin
      expect(preconnectSpy).toHaveBeenCalledWith('https://cdn.jsdelivr.net', {
        crossOrigin: '',
      });
    } finally {
      reactDom.preconnect = originalPreconnect;
    }
  });

  test('renders without resource APIs on React 18', async () => {
    expect(reactDom.preconnect).toBeUndefined();
    expect(reactDom.experimental_preconnect).toBeUndefined();
    await render(<YouTubeEmbed videoid="sSbDtQTtwBY" />);
    await expect.element(page.locator('lite-youtube')).toBeAttached();
  });

  test('renders script elements generated by third-party-capital', async () => {
    await render(<YouTubeEmbed videoid="sSbDtQTtwBY" />);

    const scriptLocator = page.locator("script[src*='lite-yt-embed']");

    await expect.element(scriptLocator).toBeAttached();
  });
});
